version: '3.8'
services:
# postgres container
  db:
    container_name: postgres_db
    image: postgres:15.4-alpine3.18
    restart: always
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: marcus
    ports:
      - 5434:5432
# spring boot rest service
  users:

    container_name: users
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=marcus
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    build: .
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 40s










