openapi: 3.0.0
info:
  title: Demo for openapi
  version: 0.0.1
paths :

  /users:
    get:
      tags:
        - Users
      operationId: getUsers
      summary: retrieves all users
      description: even more of a description
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: "#/components/schemas/User"
components:
  schemas:
    User:
      type: object
      description: A User
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        userType:
          type: string




